#ifndef HW3_SHADERIMPL_HPP
#define HW3_SHADERIMPL_HPP

#include "shader.hpp"

namespace hw3 {
    namespace shaders {
        namespace impl {
            /*
             * These global variables are populated using autogenerated files created during the build
             * process. Each contains the contents of one of the GLSL files in the shaders directory.
             */
            extern const char* vertex_simple;
            extern const char* vertex_textured;
            extern const char* fragment_fixed;
            extern const char* fragment_font;
            extern const char* fragment_textured;
        }

        extern ShaderProgram fixed_program;
        extern ShaderProgram font_program;
        extern ShaderProgram textured_program;

        void init();
    }
}

#endif
